#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(pwd)"
WEB_DIR="${ROOT_DIR}/apps/web"

require_file() {
  local file="$1"
  if [ ! -f "$file" ]; then
    echo "Error: required file not found: $file"
    exit 1
  fi
}

ensure_dir() {
  mkdir -p "$1"
}

append_if_missing() {
  local file="$1"
  local text="$2"

  touch "$file"
  if ! grep -Fq "$text" "$file"; then
    printf "%s\n" "$text" >> "$file"
  fi
}

replace_file_if_different() {
  local target="$1"
  local tmp
  tmp="$(mktemp)"
  cat > "$tmp"

  if [ -f "$target" ] && cmp -s "$tmp" "$target"; then
    rm -f "$tmp"
    return 0
  fi

  mkdir -p "$(dirname "$target")"
  mv "$tmp" "$target"
}

patch_root_tsconfig() {
  node <<'EOF'
const fs = require('fs');
const path = require('path');

const file = path.resolve('tsconfig.json');
const json = JSON.parse(fs.readFileSync(file, 'utf8'));

json.references ||= [];
const wanted = { path: './apps/web' };
const exists = json.references.some((r) => r && r.path === wanted.path);

if (!exists) {
  json.references.push(wanted);
  fs.writeFileSync(file, JSON.stringify(json, null, 2) + '\n');
}
EOF
}

patch_root_readme() {
  local marker="## Web App"
  if ! grep -Fq "$marker" README.md; then
    cat >> README.md <<'EOF'

## Web App

`apps/web` is the TanStack Start + SolidJS web application.

Current posture:
- full-stack Solid app shell
- file-based routes
- route tree generated by TanStack Router plugin
- auth intentionally deferred to a later overlay layer
EOF
  fi
}

main() {
  require_file "${ROOT_DIR}/package.json"
  require_file "${ROOT_DIR}/tsconfig.json"
  require_file "${ROOT_DIR}/turbo.json"
  require_file "${ROOT_DIR}/biome.jsonc"

  ensure_dir "${WEB_DIR}/public"
  ensure_dir "${WEB_DIR}/src/routes"
  ensure_dir "${WEB_DIR}/src/components/layout"
  ensure_dir "${WEB_DIR}/src/components/ui"
  ensure_dir "${WEB_DIR}/src/lib/query"
  ensure_dir "${WEB_DIR}/src/lib/seo"
  ensure_dir "${WEB_DIR}/src/styles"
  ensure_dir "${WEB_DIR}/src/tests"

  replace_file_if_different "${WEB_DIR}/package.json" <<'EOF'
{
  "name": "@repo/web",
  "version": "0.0.0",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "vite dev --port 3000",
    "build": "vite build",
    "start": "node .output/server/index.mjs",
    "typecheck": "tsc -b --pretty false",
    "lint": "biome check .",
    "test": "vitest run",
    "test:watch": "vitest",
    "test:ui": "vitest --ui"
  },
  "dependencies": {
    "@repo/contracts": "workspace:*",
    "@repo/shared": "workspace:*",
    "@solidjs/meta": "^0.29.4",
    "@tanstack/solid-query": "^5.90.2",
    "@tanstack/solid-router": "^1.168.1",
    "@tanstack/solid-start": "^1.167.15",
    "solid-js": "^1.9.9"
  },
  "devDependencies": {
    "@tanstack/router-plugin": "^1.167.12",
    "@testing-library/jest-dom": "^6.8.0",
    "@solidjs/testing-library": "^0.8.10",
    "@types/node": "^24.3.0",
    "jsdom": "^26.1.0",
    "typescript": "^5.9.2",
    "vite": "^7.1.3",
    "vite-plugin-solid": "^2.11.8",
    "vitest": "^3.2.4"
  }
}
EOF

  replace_file_if_different "${WEB_DIR}/tsconfig.json" <<'EOF'
{
  "extends": "../../packages/typescript-config/base.json",
  "compilerOptions": {
    "jsx": "preserve",
    "jsxImportSource": "solid-js",
    "target": "ES2022",
    "lib": ["ES2023", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "rootDir": "src",
    "outDir": "dist",
    "types": ["vite/client", "vitest/globals", "node"],
    "verbatimModuleSyntax": false
  },
  "references": [
    { "path": "../../packages/shared" },
    { "path": "../../packages/contracts" }
  ],
  "include": ["src", "vite.config.ts", "vitest.config.ts"]
}
EOF

  replace_file_if_different "${WEB_DIR}/vite.config.ts" <<'EOF'
import { defineConfig } from "vite";
import { tanstackRouter } from "@tanstack/router-plugin/vite";
import { tanstackStart } from "@tanstack/solid-start/plugin/vite";
import solidPlugin from "vite-plugin-solid";

export default defineConfig({
  plugins: [
    tanstackRouter({
      target: "solid",
      autoCodeSplitting: true,
      routesDirectory: "./src/routes",
      generatedRouteTree: "./src/routeTree.gen.ts"
    }),
    tanstackStart(),
    solidPlugin({ ssr: true })
  ]
});
EOF

  replace_file_if_different "${WEB_DIR}/vitest.config.ts" <<'EOF'
import { defineConfig } from "vitest/config";
import solidPlugin from "vite-plugin-solid";

export default defineConfig({
  plugins: [solidPlugin()],
  test: {
    environment: "jsdom",
    setupFiles: ["./src/tests/setup.ts"],
    globals: true,
    include: ["src/tests/**/*.test.ts", "src/tests/**/*.test.tsx"]
  }
});
EOF

  replace_file_if_different "${WEB_DIR}/src/tests/setup.ts" <<'EOF'
import "@testing-library/jest-dom";
EOF

  replace_file_if_different "${WEB_DIR}/src/router.tsx" <<'EOF'
import { createRouter } from "@tanstack/solid-router";
import { routeTree } from "./routeTree.gen";

export function getRouter() {
  const router = createRouter({
    routeTree,
    scrollRestoration: true,
    defaultPreload: "intent"
  });

  return router;
}

declare module "@tanstack/solid-router" {
  interface Register {
    router: ReturnType<typeof getRouter>;
  }
}
EOF

  replace_file_if_different "${WEB_DIR}/src/routes/__root.tsx" <<'EOF'
import {
  HeadContent,
  Outlet,
  Scripts,
  createRootRoute
} from "@tanstack/solid-router";
import { Suspense } from "solid-js";
import { HydrationScript } from "solid-js/web";
import appCss from "../styles/app.css?url";

export const Route = createRootRoute({
  head: () => ({
    meta: [
      { charSet: "utf-8" },
      {
        name: "viewport",
        content: "width=device-width, initial-scale=1"
      },
      {
        title: "Monorepo Web"
      },
      {
        name: "description",
        content: "TanStack Start + Solid web application"
      }
    ],
    links: [{ rel: "stylesheet", href: appCss }]
  }),
  shellComponent: RootDocument
});

function RootDocument(props: { children: unknown }) {
  return (
    <html lang="en">
      <head>
        <HydrationScript />
        <HeadContent />
      </head>
      <body>
        <Suspense>{props.children}</Suspense>
        <Scripts />
      </body>
    </html>
  );
}
EOF

  replace_file_if_different "${WEB_DIR}/src/routes/index.tsx" <<'EOF'
import { createFileRoute } from "@tanstack/solid-router";
import { createServerFn } from "@tanstack/solid-start";

const getGreeting = createServerFn({ method: "GET" }).handler(async () => {
  return "Web app scaffolded successfully.";
});

export const Route = createFileRoute("/")({
  loader: () => getGreeting(),
  component: HomePage
});

function HomePage() {
  const greeting = Route.useLoaderData();

  return (
    <main class="min-h-screen bg-slate-950 text-slate-100">
      <div class="mx-auto flex min-h-screen max-w-5xl flex-col justify-center gap-6 px-6 py-16">
        <p class="text-sm uppercase tracking-[0.2em] text-slate-400">
          TanStack Start + Solid
        </p>
        <h1 class="text-4xl font-semibold tracking-tight sm:text-5xl">
          {greeting()}
        </h1>
        <p class="max-w-2xl text-base leading-7 text-slate-300">
          This is the initial web layer for the monorepo. Tailwind, Kobalte,
          and Keycloak auth will be added by later overlays.
        </p>
      </div>
    </main>
  );
}
EOF

  replace_file_if_different "${WEB_DIR}/src/styles/app.css" <<'EOF'
:root {
  color-scheme: dark;
}

* {
  box-sizing: border-box;
}

html,
body {
  margin: 0;
  padding: 0;
  font-family:
    Inter,
    ui-sans-serif,
    system-ui,
    -apple-system,
    BlinkMacSystemFont,
    "Segoe UI",
    sans-serif;
  background: #020617;
  color: #f8fafc;
}
EOF

  replace_file_if_different "${WEB_DIR}/src/components/layout/app-shell.tsx" <<'EOF'
import type { JSX } from "solid-js";

export function AppShell(props: { children: JSX.Element }) {
  return (
    <div class="min-h-screen bg-slate-950 text-slate-100">
      {props.children}
    </div>
  );
}
EOF

  replace_file_if_different "${WEB_DIR}/src/lib/query/client.ts" <<'EOF'
import { QueryClient } from "@tanstack/solid-query";

export function createAppQueryClient() {
  return new QueryClient();
}
EOF

  replace_file_if_different "${WEB_DIR}/src/lib/seo/defaults.ts" <<'EOF'
export const DEFAULT_SEO = {
  title: "Monorepo Web",
  description: "TanStack Start + Solid web application"
};
EOF

  append_if_missing "${WEB_DIR}/public/.gitkeep" ""

  patch_root_tsconfig
  patch_root_readme

  echo "Scaffolded apps/web as TanStack Start + Solid."
  echo
  echo "Next steps:"
  echo "  1. bun install"
  echo "  2. bun run --filter @repo/web dev"
  echo "  3. then apply the Tailwind/Kobalte overlay"
}

main "$@"